export type HomeNursingCertificate = {
  no: string;
  refno: string;
  examDate: string;
  examName: string;
  examSjamId: string;
  examIc: string;
  result: "Passed" | "Failed";
  examTypeEn: string;
  examTypeMs: string;
  examUnit: string;
  dateOfIssue: string;
  state: string;
  issued: number;
  certNo: string;
};

export const HOME_NURSING_BATCH = {
  title: "Summary Listing of Membership Documentation",
  intro:
    "Reference to \"Summary Listing of Membership Documentation\", below are the details of the processed documentations.",
  nhqCode: "KSB260001, KPS260012, KSTU260010, KSTS260014 & SDE260005",
  idReference: "4279",
  certificateCount: 12,
  notes:
    "Upon receiving the completed Certificates, kindly check and notify Processing Centre within 30 days from date of courier. PC will not be held liable for any mistakes in the applicants details there after the stipulated time given.",
} as const;

export const HOME_NURSING_CERTIFICATES: HomeNursingCertificate[] = [
  {
    no: "001",
    refno: "KSB260001",
    examDate: "09-May-26",
    examName: "QUEK JIA QI",
    examSjamId: "",
    examIc: "090311-05-0462",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KSB01 - IBU PEJABAT KSB",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379649",
  },
  {
    no: "002",
    refno: "KSB260002",
    examDate: "09-May-26",
    examName: "KHOO SING RHONG",
    examSjamId: "",
    examIc: "920415-10-5123",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KSB01 - IBU PEJABAT KSB",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379650",
  },
  {
    no: "003",
    refno: "KPS260012",
    examDate: "09-May-26",
    examName: "CHOO LE YUEN",
    examSjamId: "",
    examIc: "881227-10-5774",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KPS01 - IBU PEJABAT KPS",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379651",
  },
  {
    no: "004",
    refno: "KPS260013",
    examDate: "09-May-26",
    examName: "CHIN HONG CHER",
    examSjamId: "",
    examIc: "910303-10-5194",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KPS04 - KUALA SELANGOR",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379652",
  },
  {
    no: "005",
    refno: "KSTU260010",
    examDate: "09-May-26",
    examName: "TAN HUNG HONG",
    examSjamId: "",
    examIc: "990301-10-5597",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KSTU02 - HULU LANGAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379653",
  },
  {
    no: "006",
    refno: "KSTU260011",
    examDate: "09-May-26",
    examName: "LAI ZHI QI",
    examSjamId: "",
    examIc: "021007-10-1645",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KSTU02 - HULU LANGAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379654",
  },
  {
    no: "007",
    refno: "KSTS260014",
    examDate: "09-May-26",
    examName: "ONG MEI CHIN",
    examSjamId: "",
    examIc: "910918-10-5122",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KSTS02 - KUALA LANGAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379655",
  },
  {
    no: "008",
    refno: "KSTS260015",
    examDate: "09-May-26",
    examName: "CHAN WUN SUM",
    examSjamId: "",
    examIc: "890922-10-5138",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "KSTS03 - SEPANG",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379656",
  },
  {
    no: "009",
    refno: "SDE260005",
    examDate: "09-May-26",
    examName: "LIM HUEY WEN",
    examSjamId: "",
    examIc: "950612-10-5012",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "S01 - IBU PEJABAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379657",
  },
  {
    no: "010",
    refno: "SDE260006",
    examDate: "09-May-26",
    examName: "HO WENG KONG",
    examSjamId: "",
    examIc: "850616-10-5075",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "S01 - IBU PEJABAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379658",
  },
  {
    no: "011",
    refno: "SDE260007",
    examDate: "09-May-26",
    examName: "CHONG MUN YEE",
    examSjamId: "",
    examIc: "031209-10-1178",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "S01 - IBU PEJABAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379659",
  },
  {
    no: "012",
    refno: "SDE260008",
    examDate: "09-May-26",
    examName: "MOHAMMAD FIKRI BIN ABDULLAH",
    examSjamId: "",
    examIc: "030816-10-5933",
    result: "Passed",
    examTypeEn: "Preliminary Home Nursing",
    examTypeMs: "Perawatan Asas di Rumah",
    examUnit: "S01 - IBU PEJABAT",
    dateOfIssue: "26-Jun-26",
    state: "Selangor Darul Ehsan",
    issued: 0,
    certNo: "379660",
  },
];
