export type PastEventAlbum = {
  id: string;
  title: string;
  /** ISO date YYYY-MM-DD for sorting and filters */
  eventDate: string;
  dateLabel: string;
  location: string;
  tag: string;
  summary: string;
  coverImage: "community" | "ambulance";
  photoCount: number;
  /** Optional custom image URL */
  customImageUrl?: string;
  /** Optional organizer name override */
  organizer?: string;
};

export const pastEventAlbums: PastEventAlbum[] = [
  {
    id: "bls-mppwp-2025",
    title: "2025 Basic Life Support Course MPPWP",
    eventDate: "2025-08-09",
    dateLabel: "9 August 2025",
    location: "MPPWP",
    tag: "Training",
    summary: "Basic Life Support accreditation course for MPPWP staff and personnel.",
    coverImage: "ambulance",
    photoCount: 12,
    customImageUrl: "https://scontent-ord5-1.xx.fbcdn.net/v/t39.30808-6/529748731_1080561777603413_7728947610022874242_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=b96d88&_nc_ohc=l-9hYBGt4Q0Q7kNvwHZ8QXo&_nc_oc=AdozmfPFc0BlOvZnV8gT-QBHgZ2E1CjNkd-rUlMU7GAcE3Ru1Lt5FrBFKgysuPIJ1Ik&_nc_zt=23&_nc_ht=scontent-ord5-1.xx&_nc_gid=Sx4Rc5_XBddOUGc5TteFZQ&_nc_ss=7f289&oh=00_Af7Kq9AREEhdFwLWh4NwjSj1_z1o7IW0NFPbtEHVPRw2qg&oe=6A157A78",
    organizer: "SJAM KSTU",
  },
  {
    id: "pusat-jagaan-megah-2025",
    title: "Pusat Jagaan Megah Kanak Orang Asli",
    eventDate: "2025-08-03",
    dateLabel: "3 August 2025",
    location: "Pusat Jagaan Megah",
    tag: "Community Care",
    summary: "Healthcare outreach and support visit to indigenous children care center.",
    coverImage: "community",
    photoCount: 14,
  },
  {
    id: "mobile-clinic-hulu-yam-2025",
    title: "Mobile Clinic at Hulu Yam",
    eventDate: "2025-08-03",
    dateLabel: "3 August 2025",
    location: "Hulu Yam",
    tag: "Mobile Clinic",
    summary: "Medical consultation and health screening for underserved Hulu Yam community.",
    coverImage: "community",
    photoCount: 16,
  },
  {
    id: "ocu-free-glasses-2025",
    title: "12th Mobile Eye Test & Free Glasses Initiative",
    eventDate: "2025-08-03",
    dateLabel: "3 August 2025",
    location: "Selangor",
    tag: "Ophthalmic Care",
    summary: "Free eye screening and prescription glasses distribution program across Selangor.",
    coverImage: "community",
    photoCount: 18,
  },
  {
    id: "junior-hero-2025",
    title: "AGMO Junior Hero in Action",
    eventDate: "2025-08-03",
    dateLabel: "3 August 2025",
    location: "AGMO Facility",
    tag: "Youth Programme",
    summary: "Cadet and youth volunteer activity and recognition programme.",
    coverImage: "community",
    photoCount: 11,
  },
  {
    id: "train-trainer-2025",
    title: "Train the Trainer Course",
    eventDate: "2025-08-02",
    dateLabel: "2 August 2025",
    location: "SJAM Training Center",
    tag: "Training",
    summary: "Instructor certification and train-the-trainer programme for first aid trainers.",
    coverImage: "ambulance",
    photoCount: 13,
  },
  {
    id: "pickle-cup-2025",
    title: "St John Charity Pickle Cup",
    eventDate: "2025-08-02",
    dateLabel: "2 August 2025",
    location: "Sports Venue, Selangor",
    tag: "Community Event",
    summary: "Charity pickle ball tournament and community sports event.",
    coverImage: "community",
    photoCount: 19,
  },
  {
    id: "kindergarten-first-aid-2025",
    title: "First Aid Experience for Kindergarten",
    eventDate: "2025-07-29",
    dateLabel: "29 July 2025",
    location: "Kindergarten",
    tag: "Education",
    summary: "Hands-on first aid awareness and basic safety training for young children.",
    coverImage: "ambulance",
    photoCount: 9,
  },
  {
    id: "school-eye-care-2025",
    title: "Ophthalmic Care in School",
    eventDate: "2025-07-24",
    dateLabel: "24 July 2025",
    location: "School",
    tag: "Ophthalmic Care",
    summary: "Eye screening and vision health programme at local schools.",
    coverImage: "community",
    photoCount: 12,
  },
  {
    id: "training-center-launch-2025",
    title: "Launching of SJAM-SDE State Training Center",
    eventDate: "2025-07-21",
    dateLabel: "21 July 2025",
    location: "SJAM Training Center",
    tag: "Milestone",
    summary: "Official inauguration of new state-of-the-art training facility.",
    coverImage: "ambulance",
    photoCount: 24,
  },
  {
    id: "charity-dinner-2025",
    title: "State Building Fund Charity Dinner",
    eventDate: "2025-07-20",
    dateLabel: "20 July 2025",
    location: "Venue, Selangor",
    tag: "Fundraising",
    summary: "Gala dinner and fundraising event for SJAM-SDE building expansion.",
    coverImage: "community",
    photoCount: 22,
  },
  {
    id: "care-home-eye-care-2025",
    title: "Ophthalmic Care at Sweet Care Home",
    eventDate: "2025-07-20",
    dateLabel: "20 July 2025",
    location: "Sweet Care Home",
    tag: "Ophthalmic Care",
    summary: "Eye care services and vision screening for elderly care home residents.",
    coverImage: "community",
    photoCount: 10,
  },
  {
    id: "istiadat-2025",
    title: "Istiadat Penganugerahan",
    eventDate: "2025-07-19",
    dateLabel: "19 July 2025",
    location: "Selangor",
    tag: "Award Ceremony",
    summary: "Awards and recognition ceremony for volunteers and members.",
    coverImage: "community",
    photoCount: 15,
  },
  {
    id: "bodhi-homecare-2025",
    title: "Ophthalmic Care at Bodhi Homecare",
    eventDate: "2025-07-05",
    dateLabel: "5 July 2025",
    location: "Bodhi Homecare",
    tag: "Ophthalmic Care",
    summary: "Eye screening and care services at Bodhi Homecare facility.",
    coverImage: "community",
    photoCount: 11,
  },
  {
    id: "ocu-revisit-2025",
    title: "Ophthalmic Care Revisit",
    eventDate: "2025-06-28",
    dateLabel: "28 June 2025",
    location: "Selangor",
    tag: "Ophthalmic Care",
    summary: "Follow-up visit and continuous eye care programme.",
    coverImage: "community",
    photoCount: 8,
  },
  {
    id: "intl-st-john-day-2025",
    title: "International St John Day",
    eventDate: "2025-06-24",
    dateLabel: "24 June 2025",
    location: "SJAM HQ, Selangor",
    tag: "Community",
    summary: "Celebration and recognition of International St John Day.",
    coverImage: "community",
    photoCount: 20,
  },
  {
    id: "good-samaritan-ocu-2025",
    title: "Ophthalmic Care at Good Samaritan Home",
    eventDate: "2025-06-21",
    dateLabel: "21 June 2025",
    location: "Good Samaritan Home",
    tag: "Ophthalmic Care",
    summary: "Eye care and health screening for care home residents.",
    coverImage: "community",
    photoCount: 12,
  },
  {
    id: "junior-xplorer-2025",
    title: "Junior Xplorer AGMO Junior",
    eventDate: "2025-06-21",
    dateLabel: "21 June 2025",
    location: "AGMO Facility",
    tag: "Youth Programme",
    summary: "Exploratory youth activity and cadet engagement programme.",
    coverImage: "community",
    photoCount: 14,
  },
  {
    id: "tiam-yam-ocu-2025",
    title: "Ophthalmic Care at Tiam Yam Toh Teng Klang",
    eventDate: "2025-06-14",
    dateLabel: "14 June 2025",
    location: "Tiam Yam Toh Teng, Klang",
    tag: "Ophthalmic Care",
    summary: "Community eye screening and vision care outreach.",
    coverImage: "community",
    photoCount: 10,
  },
  {
    id: "kebajikan-anak-ocu-2025",
    title: "Ophthalmic Care at Kebajikan Anak Yatim Mary",
    eventDate: "2025-06-08",
    dateLabel: "8 June 2025",
    location: "Kebajikan Anak Yatim Mary",
    tag: "Ophthalmic Care",
    summary: "Eye care services for orphanage children.",
    coverImage: "community",
    photoCount: 9,
  },
  {
    id: "first-aid-competition-2025",
    title: "64th First Aid & Home Nursing Competition",
    eventDate: "2025-06-02",
    dateLabel: "2 June 2025",
    location: "Venue, Selangor",
    tag: "Competition",
    summary: "Annual first aid and home nursing skills competition for teams.",
    coverImage: "ambulance",
    photoCount: 25,
  },
  {
    id: "kps-cadet-training-2025",
    title: "KPS Cadet Training Course",
    eventDate: "2025-05-24",
    dateLabel: "24 May 2025",
    location: "Training Center",
    tag: "Training",
    summary: "Cadet training course for young volunteers.",
    coverImage: "ambulance",
    photoCount: 13,
  },
  {
    id: "mock-exercise-2025",
    title: "Mock Exercise",
    eventDate: "2025-01-23",
    dateLabel: "23 January 2025",
    location: "Selangor",
    tag: "Training",
    summary: "Disaster response and emergency preparedness mock exercise.",
    coverImage: "ambulance",
    photoCount: 18,
  },
  {
    id: "little-sisters-2023",
    title: "Visit Pusat Jagaan Little Sisters",
    eventDate: "2023-08-07",
    dateLabel: "7 August 2023",
    location: "Pusat Jagaan Little Sisters",
    tag: "Community Care",
    summary: "Healthcare outreach visit to care facility.",
    coverImage: "community",
    photoCount: 12,
  },
  {
    id: "cancer-screening-2023",
    title: "Cancer Screening",
    eventDate: "2023-06-20",
    dateLabel: "20 June 2023",
    location: "Selangor",
    tag: "Health Screening",
    summary: "Community cancer awareness and screening programme.",
    coverImage: "community",
    photoCount: 14,
  },
  {
    id: "air-attendant-2023",
    title: "Air Attendant Course",
    eventDate: "2023-06-20",
    dateLabel: "20 June 2023",
    location: "Training Center",
    tag: "Training",
    summary: "Specialized first aid course for airline cabin crew.",
    coverImage: "ambulance",
    photoCount: 11,
  },
  {
    id: "blood-drive-nationwide-2023",
    title: "Nationwide Blood Donation Drive",
    eventDate: "2023-06-14",
    dateLabel: "14 June 2023",
    location: "Multiple locations, Selangor",
    tag: "Blood Donation",
    summary: "Large-scale blood donation campaign across Selangor.",
    coverImage: "community",
    photoCount: 21,
  },
  {
    id: "mass-cpr-2023",
    title: "Mass CPR Awareness",
    eventDate: "2023-03-09",
    dateLabel: "9 March 2023",
    location: "Selangor",
    tag: "Training",
    summary: "Public awareness campaign for CPR techniques.",
    coverImage: "ambulance",
    photoCount: 16,
  },
  {
    id: "blood-drive-2023",
    title: "Blood Donation Drive",
    eventDate: "2023-03-09",
    dateLabel: "9 March 2023",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Community blood donation and health screening.",
    coverImage: "community",
    photoCount: 13,
  },
  {
    id: "batang-kali-2022",
    title: "Batang Kali Landslide",
    eventDate: "2022-03-09",
    dateLabel: "9 March 2022",
    location: "Batang Kali",
    tag: "Disaster Relief",
    summary: "Emergency response and disaster relief for landslide incident.",
    coverImage: "ambulance",
    photoCount: 22,
  },
  {
    id: "mobile-clinic-2022",
    title: "Mobile Clinic – Chik Sin Thong Old Folks Home Selangor",
    eventDate: "2022-03-09",
    dateLabel: "9 March 2022",
    location: "Chik Sin Thong Old Folks Home",
    tag: "Mobile Clinic",
    summary: "Mobile medical clinic visit to elderly care home.",
    coverImage: "community",
    photoCount: 11,
  },
  {
    id: "flood-relief-2021",
    title: "Flood Relief Taman Sri Muda",
    eventDate: "2021-03-09",
    dateLabel: "9 March 2021",
    location: "Taman Sri Muda",
    tag: "Disaster Relief",
    summary: "Emergency relief and assistance for flood victims.",
    coverImage: "community",
    photoCount: 19,
  },
  {
    id: "covid-standby-2020",
    title: "Covid-19 Standby",
    eventDate: "2020-03-09",
    dateLabel: "9 March 2020",
    location: "Selangor",
    tag: "Public Duty",
    summary: "Emergency response and medical standby during Covid-19 pandemic.",
    coverImage: "ambulance",
    photoCount: 17,
  },
  {
    id: "blood-donation-6-2019",
    title: "Blood Donation 6.0",
    eventDate: "2019-12-16",
    dateLabel: "16 December 2019",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Annual blood donation campaign drive.",
    coverImage: "community",
    photoCount: 12,
  },
  {
    id: "blood-donation-5-2018",
    title: "Blood Donation 5.0",
    eventDate: "2018-12-21",
    dateLabel: "21 December 2018",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Continuing series of annual blood donation initiatives.",
    coverImage: "community",
    photoCount: 13,
  },
  {
    id: "blood-donation-4-2017",
    title: "Blood Donation 4.0",
    eventDate: "2017-12-21",
    dateLabel: "21 December 2017",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Community blood donation and health awareness campaign.",
    coverImage: "community",
    photoCount: 11,
  },
  {
    id: "blood-donation-3-2016",
    title: "Blood Donation 3.0",
    eventDate: "2016-12-21",
    dateLabel: "21 December 2016",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Blood donation drive supporting national blood bank.",
    coverImage: "community",
    photoCount: 10,
  },
  {
    id: "blood-donation-2-2015",
    title: "Blood Donation 2.0",
    eventDate: "2015-12-21",
    dateLabel: "21 December 2015",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Annual blood donation and community engagement event.",
    coverImage: "community",
    photoCount: 9,
  },
  {
    id: "blood-donation-2014",
    title: "Blood Donation Drive",
    eventDate: "2014-12-21",
    dateLabel: "21 December 2014",
    location: "Selangor",
    tag: "Blood Donation",
    summary: "Community blood donation campaign.",
    coverImage: "community",
    photoCount: 8,
  },
  {
    id: "air-attendant-2013",
    title: "Air Attendant 2013",
    eventDate: "2013-12-16",
    dateLabel: "16 December 2013",
    location: "Training Center",
    tag: "Training",
    summary: "Specialized training course for airline crew.",
    coverImage: "ambulance",
    photoCount: 10,
  },
];

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

export function getPastEventAlbum(id: string) {
  return pastEventAlbums.find((a) => a.id === id);
}

export function getGalleryYears() {
  const years = [...new Set(pastEventAlbums.map((a) => a.eventDate.slice(0, 4)))];
  return years.sort((a, b) => Number(b) - Number(a));
}

export function getGalleryMonthsForYear(year: string) {
  const months = pastEventAlbums
    .filter((a) => a.eventDate.startsWith(year))
    .map((a) => a.eventDate.slice(5, 7));
  return [...new Set(months)].sort((a, b) => Number(b) - Number(a));
}

export function monthLabel(month: string) {
  const index = Number(month) - 1;
  return MONTH_NAMES[index] ?? month;
}

export function filterPastEventAlbums(year: string, month: string) {
  return [...pastEventAlbums]
    .filter((album) => {
      if (year !== "all" && !album.eventDate.startsWith(year)) return false;
      if (month !== "all" && album.eventDate.slice(5, 7) !== month) return false;
      return true;
    })
    .sort((a, b) => b.eventDate.localeCompare(a.eventDate));
}
