/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as QualifiedTrainersRouteImport } from './routes/qualified-trainers'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonationStatusRouteImport } from './routes/donation-status'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as Ambulance24hrRouteImport } from './routes/ambulance-24hr'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as OcuDeploymentIdRouteImport } from './routes/ocu.$deploymentId'
import { Route as MobileClinicEventIdRouteImport } from './routes/mobile-clinic.$eventId'
import { Route as GalleryAlbumIdRouteImport } from './routes/gallery.$albumId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DonationsLoginRouteImport } from './routes/donations.login'
import { Route as DonationsEntryRouteImport } from './routes/donations.entry'
import { Route as DonationProjectIdRouteImport } from './routes/donation.$projectId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AboutQualifiedTrainersRouteImport } from './routes/about/qualified-trainers'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifiedTrainersRoute = QualifiedTrainersRouteImport.update({
  id: '/qualified-trainers',
  path: '/qualified-trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationStatusRoute = DonationStatusRouteImport.update({
  id: '/donation-status',
  path: '/donation-status',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const Ambulance24hrRoute = Ambulance24hrRouteImport.update({
  id: '/ambulance-24hr',
  path: '/ambulance-24hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const OcuDeploymentIdRoute = OcuDeploymentIdRouteImport.update({
  id: '/ocu/$deploymentId',
  path: '/ocu/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileClinicEventIdRoute = MobileClinicEventIdRouteImport.update({
  id: '/mobile-clinic/$eventId',
  path: '/mobile-clinic/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAlbumIdRoute = GalleryAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => GalleryRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const DonationsLoginRoute = DonationsLoginRouteImport.update({
  id: '/donations/login',
  path: '/donations/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsEntryRoute = DonationsEntryRouteImport.update({
  id: '/donations/entry',
  path: '/donations/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationProjectIdRoute = DonationProjectIdRouteImport.update({
  id: '/donation/$projectId',
  path: '/donation/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AboutQualifiedTrainersRoute = AboutQualifiedTrainersRouteImport.update({
  id: '/qualified-trainers',
  path: '/qualified-trainers',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/ambulance-24hr': typeof Ambulance24hrRoute
  '/courses': typeof CoursesRouteWithChildren
  '/donate': typeof DonateRoute
  '/donation-status': typeof DonationStatusRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/programs': typeof ProgramsRoute
  '/qualified-trainers': typeof QualifiedTrainersRoute
  '/schedule': typeof ScheduleRoute
  '/volunteer': typeof VolunteerRoute
  '/about/qualified-trainers': typeof AboutQualifiedTrainersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/donation/$projectId': typeof DonationProjectIdRoute
  '/donations/entry': typeof DonationsEntryRoute
  '/donations/login': typeof DonationsLoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/gallery/$albumId': typeof GalleryAlbumIdRoute
  '/mobile-clinic/$eventId': typeof MobileClinicEventIdRoute
  '/ocu/$deploymentId': typeof OcuDeploymentIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/ambulance-24hr': typeof Ambulance24hrRoute
  '/donate': typeof DonateRoute
  '/donation-status': typeof DonationStatusRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/programs': typeof ProgramsRoute
  '/qualified-trainers': typeof QualifiedTrainersRoute
  '/schedule': typeof ScheduleRoute
  '/volunteer': typeof VolunteerRoute
  '/about/qualified-trainers': typeof AboutQualifiedTrainersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/donation/$projectId': typeof DonationProjectIdRoute
  '/donations/entry': typeof DonationsEntryRoute
  '/donations/login': typeof DonationsLoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/gallery/$albumId': typeof GalleryAlbumIdRoute
  '/mobile-clinic/$eventId': typeof MobileClinicEventIdRoute
  '/ocu/$deploymentId': typeof OcuDeploymentIdRoute
  '/courses': typeof CoursesIndexRoute
  '/gallery': typeof GalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/ambulance-24hr': typeof Ambulance24hrRoute
  '/courses': typeof CoursesRouteWithChildren
  '/donate': typeof DonateRoute
  '/donation-status': typeof DonationStatusRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/programs': typeof ProgramsRoute
  '/qualified-trainers': typeof QualifiedTrainersRoute
  '/schedule': typeof ScheduleRoute
  '/volunteer': typeof VolunteerRoute
  '/about/qualified-trainers': typeof AboutQualifiedTrainersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/donation/$projectId': typeof DonationProjectIdRoute
  '/donations/entry': typeof DonationsEntryRoute
  '/donations/login': typeof DonationsLoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/gallery/$albumId': typeof GalleryAlbumIdRoute
  '/mobile-clinic/$eventId': typeof MobileClinicEventIdRoute
  '/ocu/$deploymentId': typeof OcuDeploymentIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ambulance-24hr'
    | '/courses'
    | '/donate'
    | '/donation-status'
    | '/events'
    | '/gallery'
    | '/login'
    | '/payment'
    | '/programs'
    | '/qualified-trainers'
    | '/schedule'
    | '/volunteer'
    | '/about/qualified-trainers'
    | '/courses/$courseId'
    | '/donation/$projectId'
    | '/donations/entry'
    | '/donations/login'
    | '/events/$eventId'
    | '/gallery/$albumId'
    | '/mobile-clinic/$eventId'
    | '/ocu/$deploymentId'
    | '/courses/'
    | '/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ambulance-24hr'
    | '/donate'
    | '/donation-status'
    | '/events'
    | '/login'
    | '/payment'
    | '/programs'
    | '/qualified-trainers'
    | '/schedule'
    | '/volunteer'
    | '/about/qualified-trainers'
    | '/courses/$courseId'
    | '/donation/$projectId'
    | '/donations/entry'
    | '/donations/login'
    | '/events/$eventId'
    | '/gallery/$albumId'
    | '/mobile-clinic/$eventId'
    | '/ocu/$deploymentId'
    | '/courses'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ambulance-24hr'
    | '/courses'
    | '/donate'
    | '/donation-status'
    | '/events'
    | '/gallery'
    | '/login'
    | '/payment'
    | '/programs'
    | '/qualified-trainers'
    | '/schedule'
    | '/volunteer'
    | '/about/qualified-trainers'
    | '/courses/$courseId'
    | '/donation/$projectId'
    | '/donations/entry'
    | '/donations/login'
    | '/events/$eventId'
    | '/gallery/$albumId'
    | '/mobile-clinic/$eventId'
    | '/ocu/$deploymentId'
    | '/courses/'
    | '/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  Ambulance24hrRoute: typeof Ambulance24hrRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DonateRoute: typeof DonateRoute
  DonationStatusRoute: typeof DonationStatusRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  ProgramsRoute: typeof ProgramsRoute
  QualifiedTrainersRoute: typeof QualifiedTrainersRoute
  ScheduleRoute: typeof ScheduleRoute
  VolunteerRoute: typeof VolunteerRoute
  DonationProjectIdRoute: typeof DonationProjectIdRoute
  DonationsEntryRoute: typeof DonationsEntryRoute
  DonationsLoginRoute: typeof DonationsLoginRoute
  MobileClinicEventIdRoute: typeof MobileClinicEventIdRoute
  OcuDeploymentIdRoute: typeof OcuDeploymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualified-trainers': {
      id: '/qualified-trainers'
      path: '/qualified-trainers'
      fullPath: '/qualified-trainers'
      preLoaderRoute: typeof QualifiedTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation-status': {
      id: '/donation-status'
      path: '/donation-status'
      fullPath: '/donation-status'
      preLoaderRoute: typeof DonationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance-24hr': {
      id: '/ambulance-24hr'
      path: '/ambulance-24hr'
      fullPath: '/ambulance-24hr'
      preLoaderRoute: typeof Ambulance24hrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/ocu/$deploymentId': {
      id: '/ocu/$deploymentId'
      path: '/ocu/$deploymentId'
      fullPath: '/ocu/$deploymentId'
      preLoaderRoute: typeof OcuDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-clinic/$eventId': {
      id: '/mobile-clinic/$eventId'
      path: '/mobile-clinic/$eventId'
      fullPath: '/mobile-clinic/$eventId'
      preLoaderRoute: typeof MobileClinicEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$albumId': {
      id: '/gallery/$albumId'
      path: '/$albumId'
      fullPath: '/gallery/$albumId'
      preLoaderRoute: typeof GalleryAlbumIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/donations/login': {
      id: '/donations/login'
      path: '/donations/login'
      fullPath: '/donations/login'
      preLoaderRoute: typeof DonationsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/entry': {
      id: '/donations/entry'
      path: '/donations/entry'
      fullPath: '/donations/entry'
      preLoaderRoute: typeof DonationsEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation/$projectId': {
      id: '/donation/$projectId'
      path: '/donation/$projectId'
      fullPath: '/donation/$projectId'
      preLoaderRoute: typeof DonationProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/about/qualified-trainers': {
      id: '/about/qualified-trainers'
      path: '/qualified-trainers'
      fullPath: '/about/qualified-trainers'
      preLoaderRoute: typeof AboutQualifiedTrainersRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutQualifiedTrainersRoute: typeof AboutQualifiedTrainersRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutQualifiedTrainersRoute: AboutQualifiedTrainersRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GalleryRouteChildren {
  GalleryAlbumIdRoute: typeof GalleryAlbumIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryAlbumIdRoute: GalleryAlbumIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  Ambulance24hrRoute: Ambulance24hrRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DonateRoute: DonateRoute,
  DonationStatusRoute: DonationStatusRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  ProgramsRoute: ProgramsRoute,
  QualifiedTrainersRoute: QualifiedTrainersRoute,
  ScheduleRoute: ScheduleRoute,
  VolunteerRoute: VolunteerRoute,
  DonationProjectIdRoute: DonationProjectIdRoute,
  DonationsEntryRoute: DonationsEntryRoute,
  DonationsLoginRoute: DonationsLoginRoute,
  MobileClinicEventIdRoute: MobileClinicEventIdRoute,
  OcuDeploymentIdRoute: OcuDeploymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
